# Generated by Django 4.2.4 on 2023-08-17 08:53

from django.db import migrations, models
import django_backblaze_b2.storage


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_mediamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamodel',
            name='file_field',
            field=models.FileField(storage=django_backblaze_b2.storage.BackblazeB2Storage, upload_to='products/image'),
        ),
    ]
