# Generated by Django 4.2.4 on 2023-08-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaProduct',
        ),
    ]
