# Generated by Django 4.2.4 on 2023-08-15 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountModel',
            new_name='Account',
        ),
    ]
