# Generated by Django 4.2.4 on 2023-08-15 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
