# Generated by Django 4.2.4 on 2023-08-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='fullName',
            new_name='full_name',
        ),
    ]
