# Generated by Django 4.2.4 on 2023-08-25 04:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.CharField(max_length=512)),
                ('host_name', models.CharField(max_length=512)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket_id', models.CharField(max_length=512)),
                ('user_id', models.CharField(max_length=512)),
                ('joined', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=512)),
                ('is_alive', models.BooleanField(default=False)),
                ('meeting_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.meeting')),
            ],
        ),
    ]
